export const getFlagEmoji = (countryCode: string) => {
	return countryCode
		.toUpperCase()
		.replace(/./g, (char) =>
			String.fromCodePoint(char.charCodeAt(0) + 127397),
		);
};

// Splits a combined intl phone string (e.g. "+2348012345678") back into a
// dial code + local number for prefilling the PhoneField. Matches the
// longest dial code first so "+1" doesn't shadow "+234" etc.
export const splitPhoneNumber = (phone: string) => {
	if (!phone) return { dial_code: "+234", phone_number: "" };

	const match = [...country]
		.sort((a, b) => b.dial_code.length - a.dial_code.length)
		.find((c) => phone.startsWith(c.dial_code));

	if (!match) {
		return { dial_code: "+234", phone_number: phone.replace(/^\+/, "") };
	}

	return {
		dial_code: match.dial_code,
		phone_number: phone.slice(match.dial_code.length),
	};
};

export const country = [
	{ name: "Afghanistan", code: "AF", iso3: "AFG", dial_code: "+93" },
	{ name: "Albania", code: "AL", iso3: "ALB", dial_code: "+355" },
	{ name: "Algeria", code: "DZ", iso3: "DZA", dial_code: "+213" },
	{ name: "American Samoa", code: "AS", iso3: "ASM", dial_code: "+1684" },
	{ name: "Andorra", code: "AD", iso3: "AND", dial_code: "+376" },
	{ name: "Angola", code: "AO", iso3: "AGO", dial_code: "+244" },
	{ name: "Anguilla", code: "AI", iso3: "AIA", dial_code: "+1264" },
	{ name: "Antarctica", code: "AQ", iso3: "ATA", dial_code: "+672" },
	{ name: "Antigua and Barbuda", code: "AG", iso3: "ATG", dial_code: "+1268" },
	{ name: "Argentina", code: "AR", iso3: "ARG", dial_code: "+54" },
	{ name: "Armenia", code: "AM", iso3: "ARM", dial_code: "+374" },
	{ name: "Aruba", code: "AW", iso3: "ABW", dial_code: "+297" },
	{ name: "Australia", code: "AU", iso3: "AUS", dial_code: "+61" },
	{ name: "Austria", code: "AT", iso3: "AUT", dial_code: "+43" },
	{ name: "Azerbaijan", code: "AZ", iso3: "AZE", dial_code: "+994" },
	{ name: "Bahamas", code: "BS", iso3: "BHS", dial_code: "+1242" },
	{ name: "Bahrain", code: "BH", iso3: "BHR", dial_code: "+973" },
	{ name: "Bangladesh", code: "BD", iso3: "BGD", dial_code: "+880" },
	{ name: "Barbados", code: "BB", iso3: "BRB", dial_code: "+1246" },
	{ name: "Belarus", code: "BY", iso3: "BLR", dial_code: "+375" },
	{ name: "Belgium", code: "BE", iso3: "BEL", dial_code: "+32" },
	{ name: "Belize", code: "BZ", iso3: "BLZ", dial_code: "+501" },
	{ name: "Benin", code: "BJ", iso3: "BEN", dial_code: "+229" },
	{ name: "Bermuda", code: "BM", iso3: "BMU", dial_code: "+1441" },
	{ name: "Bhutan", code: "BT", iso3: "BTN", dial_code: "+975" },
	{ name: "Bolivia", code: "BO", iso3: "BOL", dial_code: "+591" },
	{
		name: "Bosnia and Herzegovina",
		code: "BA",
		iso3: "BIH",
		dial_code: "+387",
	},
	{ name: "Botswana", code: "BW", iso3: "BWA", dial_code: "+267" },
	{ name: "Brazil", code: "BR", iso3: "BRA", dial_code: "+55" },
	{ name: "Brunei", code: "BN", iso3: "BRN", dial_code: "+673" },
	{ name: "Bulgaria", code: "BG", iso3: "BGR", dial_code: "+359" },
	{ name: "Burkina Faso", code: "BF", iso3: "BFA", dial_code: "+226" },
	{ name: "Burundi", code: "BI", iso3: "BDI", dial_code: "+257" },
	{ name: "Cambodia", code: "KH", iso3: "KHM", dial_code: "+855" },
	{ name: "Cameroon", code: "CM", iso3: "CMR", dial_code: "+237" },
	{ name: "Canada", code: "CA", iso3: "CAN", dial_code: "+1" },
	{ name: "Cape Verde", code: "CV", iso3: "CPV", dial_code: "+238" },
	{ name: "Cayman Islands", code: "KY", iso3: "CYM", dial_code: "+1345" },
	{
		name: "Central African Republic",
		code: "CF",
		iso3: "CAF",
		dial_code: "+236",
	},
	{ name: "Chad", code: "TD", iso3: "TCD", dial_code: "+235" },
	{ name: "Chile", code: "CL", iso3: "CHL", dial_code: "+56" },
	{ name: "China", code: "CN", iso3: "CHN", dial_code: "+86" },
	{ name: "Colombia", code: "CO", iso3: "COL", dial_code: "+57" },
	{ name: "Comoros", code: "KM", iso3: "COM", dial_code: "+269" },
	{ name: "Congo", code: "CG", iso3: "COG", dial_code: "+242" },
	{ name: "Congo (DRC)", code: "CD", iso3: "COD", dial_code: "+243" },
	{ name: "Costa Rica", code: "CR", iso3: "CRC", dial_code: "+506" },
	{ name: "Croatia", code: "HR", iso3: "HRV", dial_code: "+385" },
	{ name: "Cuba", code: "CU", iso3: "CUB", dial_code: "+53" },
	{ name: "Cyprus", code: "CY", iso3: "CYP", dial_code: "+357" },
	{ name: "Czech Republic", code: "CZ", iso3: "CZE", dial_code: "+420" },
	{ name: "Denmark", code: "DK", iso3: "DNK", dial_code: "+45" },
	{ name: "Djibouti", code: "DJ", iso3: "DJI", dial_code: "+253" },
	{ name: "Dominica", code: "DM", iso3: "DMA", dial_code: "+1767" },
	{ name: "Dominican Republic", code: "DO", iso3: "DOM", dial_code: "+1809" },
	{ name: "Ecuador", code: "EC", iso3: "ECU", dial_code: "+593" },
	{ name: "Egypt", code: "EG", iso3: "EGY", dial_code: "+20" },
	{ name: "El Salvador", code: "SV", iso3: "SLV", dial_code: "+503" },
	{ name: "Equatorial Guinea", code: "GQ", iso3: "GNQ", dial_code: "+240" },
	{ name: "Eritrea", code: "ER", iso3: "ERI", dial_code: "+291" },
	{ name: "Estonia", code: "EE", iso3: "EST", dial_code: "+372" },
	{ name: "Eswatini", code: "SZ", iso3: "SWZ", dial_code: "+268" },
	{ name: "Ethiopia", code: "ET", iso3: "ETH", dial_code: "+251" },
	{ name: "Fiji", code: "FJ", iso3: "FJI", dial_code: "+679" },
	{ name: "Finland", code: "FI", iso3: "FIN", dial_code: "+358" },
	{ name: "France", code: "FR", iso3: "FRA", dial_code: "+33" },
	{ name: "Gabon", code: "GA", iso3: "GAB", dial_code: "+241" },
	{ name: "Gambia", code: "GM", iso3: "GMB", dial_code: "+220" },
	{ name: "Georgia", code: "GE", iso3: "GEO", dial_code: "+995" },
	{ name: "Germany", code: "DE", iso3: "DEU", dial_code: "+49" },
	{ name: "Ghana", code: "GH", iso3: "GHA", dial_code: "+233" },
	{ name: "Greece", code: "GR", iso3: "GRC", dial_code: "+30" },
	{ name: "Grenada", code: "GD", iso3: "GRD", dial_code: "+1473" },
	{ name: "Guatemala", code: "GT", iso3: "GTM", dial_code: "+502" },
	{ name: "Guinea", code: "GN", iso3: "GIN", dial_code: "+224" },
	{ name: "Guinea-Bissau", code: "GW", iso3: "GNB", dial_code: "+245" },
	{ name: "Guyana", code: "GY", iso3: "GUY", dial_code: "+592" },
	{ name: "Haiti", code: "HT", iso3: "HTI", dial_code: "+509" },
	{ name: "Honduras", code: "HN", iso3: "HND", dial_code: "+504" },
	{ name: "Hungary", code: "HU", iso3: "HUN", dial_code: "+36" },
	{ name: "Iceland", code: "IS", iso3: "ISL", dial_code: "+354" },
	{ name: "India", code: "IN", iso3: "IND", dial_code: "+91" },
	{ name: "Indonesia", code: "ID", iso3: "IDN", dial_code: "+62" },
	{ name: "Iran", code: "IR", iso3: "IRN", dial_code: "+98" },
	{ name: "Iraq", code: "IQ", iso3: "IRQ", dial_code: "+964" },
	{ name: "Ireland", code: "IE", iso3: "IRL", dial_code: "+353" },
	{ name: "Israel", code: "IL", iso3: "ISR", dial_code: "+972" },
	{ name: "Italy", code: "IT", iso3: "ITA", dial_code: "+39" },
	{ name: "Jamaica", code: "JM", iso3: "JAM", dial_code: "+1876" },
	{ name: "Japan", code: "JP", iso3: "JPN", dial_code: "+81" },
	{ name: "Jordan", code: "JO", iso3: "JOR", dial_code: "+962" },
	{ name: "Kazakhstan", code: "KZ", iso3: "KAZ", dial_code: "+7" },
	{ name: "Kenya", code: "KE", iso3: "KEN", dial_code: "+254" },
	{ name: "Kuwait", code: "KW", iso3: "KWT", dial_code: "+965" },
	{ name: "Kyrgyzstan", code: "KG", iso3: "KGZ", dial_code: "+996" },
	{ name: "Laos", code: "LA", iso3: "LAO", dial_code: "+856" },
	{ name: "Latvia", code: "LV", iso3: "LVA", dial_code: "+371" },
	{ name: "Lebanon", code: "LB", iso3: "LBN", dial_code: "+961" },
	{ name: "Lesotho", code: "LS", iso3: "LSO", dial_code: "+266" },
	{ name: "Liberia", code: "LR", iso3: "LBR", dial_code: "+231" },
	{ name: "Libya", code: "LY", iso3: "LBY", dial_code: "+218" },
	{ name: "Liechtenstein", code: "LI", iso3: "LIE", dial_code: "+423" },
	{ name: "Lithuania", code: "LT", iso3: "LTU", dial_code: "+370" },
	{ name: "Luxembourg", code: "LU", iso3: "LUX", dial_code: "+352" },
	{ name: "Madagascar", code: "MG", iso3: "MDG", dial_code: "+261" },
	{ name: "Malawi", code: "MW", iso3: "MWI", dial_code: "+265" },
	{ name: "Malaysia", code: "MY", iso3: "MYS", dial_code: "+60" },
	{ name: "Maldives", code: "MV", iso3: "MDV", dial_code: "+960" },
	{ name: "Mali", code: "ML", iso3: "MLI", dial_code: "+223" },
	{ name: "Malta", code: "MT", iso3: "MLT", dial_code: "+356" },
	{ name: "Mauritania", code: "MR", iso3: "MRT", dial_code: "+222" },
	{ name: "Mauritius", code: "MU", iso3: "MUS", dial_code: "+230" },
	{ name: "Mexico", code: "MX", iso3: "MEX", dial_code: "+52" },
	{ name: "Moldova", code: "MD", iso3: "MDA", dial_code: "+373" },
	{ name: "Monaco", code: "MC", iso3: "MCO", dial_code: "+377" },
	{ name: "Mongolia", code: "MN", iso3: "MNG", dial_code: "+976" },
	{ name: "Montenegro", code: "ME", iso3: "MNE", dial_code: "+382" },
	{ name: "Morocco", code: "MA", iso3: "MAR", dial_code: "+212" },
	{ name: "Mozambique", code: "MZ", iso3: "MOZ", dial_code: "+258" },
	{ name: "Myanmar", code: "MM", iso3: "MMR", dial_code: "+95" },
	{ name: "Namibia", code: "NA", iso3: "NAM", dial_code: "+264" },
	{ name: "Nepal", code: "NP", iso3: "NPL", dial_code: "+977" },
	{ name: "Netherlands", code: "NL", iso3: "NLD", dial_code: "+31" },
	{ name: "New Zealand", code: "NZ", iso3: "NZL", dial_code: "+64" },
	{ name: "Nicaragua", code: "NI", iso3: "NIC", dial_code: "+505" },
	{ name: "Niger", code: "NE", iso3: "NER", dial_code: "+227" },
	{ name: "Nigeria", code: "NG", iso3: "NGA", dial_code: "+234" },
	{ name: "North Macedonia", code: "MK", iso3: "MKD", dial_code: "+389" },
	{ name: "Norway", code: "NO", iso3: "NOR", dial_code: "+47" },
	{ name: "Oman", code: "OM", iso3: "OMN", dial_code: "+968" },
	{ name: "Pakistan", code: "PK", iso3: "PAK", dial_code: "+92" },
	{ name: "Panama", code: "PA", iso3: "PAN", dial_code: "+507" },
	{ name: "Papua New Guinea", code: "PG", iso3: "PNG", dial_code: "+675" },
	{ name: "Paraguay", code: "PY", iso3: "PRY", dial_code: "+595" },
	{ name: "Peru", code: "PE", iso3: "PER", dial_code: "+51" },
	{ name: "Philippines", code: "PH", iso3: "PHL", dial_code: "+63" },
	{ name: "Poland", code: "PL", iso3: "POL", dial_code: "+48" },
	{ name: "Portugal", code: "PT", iso3: "PRT", dial_code: "+351" },
	{ name: "Qatar", code: "QA", iso3: "QAT", dial_code: "+974" },
	{ name: "Romania", code: "RO", iso3: "ROU", dial_code: "+40" },
	{ name: "Russia", code: "RU", iso3: "RUS", dial_code: "+7" },
	{ name: "Rwanda", code: "RW", iso3: "RWA", dial_code: "+250" },
	{ name: "Saudi Arabia", code: "SA", iso3: "SAU", dial_code: "+966" },
	{ name: "Senegal", code: "SN", iso3: "SEN", dial_code: "+221" },
	{ name: "Serbia", code: "RS", iso3: "SRB", dial_code: "+381" },
	{ name: "Singapore", code: "SG", iso3: "SGP", dial_code: "+65" },
	{ name: "Slovakia", code: "SK", iso3: "SVK", dial_code: "+421" },
	{ name: "Slovenia", code: "SI", iso3: "SVN", dial_code: "+386" },
	{ name: "South Africa", code: "ZA", iso3: "ZAF", dial_code: "+27" },
	{ name: "South Korea", code: "KR", iso3: "KOR", dial_code: "+82" },
	{ name: "Spain", code: "ES", iso3: "ESP", dial_code: "+34" },
	{ name: "Sri Lanka", code: "LK", iso3: "LKA", dial_code: "+94" },
	{ name: "Sweden", code: "SE", iso3: "SWE", dial_code: "+46" },
	{ name: "Switzerland", code: "CH", iso3: "CHE", dial_code: "+41" },
	{ name: "Taiwan", code: "TW", iso3: "TWN", dial_code: "+886" },
	{ name: "Tanzania", code: "TZ", iso3: "TZA", dial_code: "+255" },
	{ name: "Thailand", code: "TH", iso3: "THA", dial_code: "+66" },
	{ name: "Tunisia", code: "TN", iso3: "TUN", dial_code: "+216" },
	{ name: "Turkey", code: "TR", iso3: "TUR", dial_code: "+90" },
	{ name: "Uganda", code: "UG", iso3: "UGA", dial_code: "+256" },
	{ name: "Ukraine", code: "UA", iso3: "UKR", dial_code: "+380" },
	{ name: "United Arab Emirates", code: "AE", iso3: "ARE", dial_code: "+971" },
	{ name: "United Kingdom", code: "GB", iso3: "GBR", dial_code: "+44" },
	{ name: "United States", code: "US", iso3: "USA", dial_code: "+1" },
	{ name: "Uruguay", code: "UY", iso3: "URY", dial_code: "+598" },
	{ name: "Uzbekistan", code: "UZ", iso3: "UZB", dial_code: "+998" },
	{ name: "Venezuela", code: "VE", iso3: "VEN", dial_code: "+58" },
	{ name: "Vietnam", code: "VN", iso3: "VNM", dial_code: "+84" },
	{ name: "Yemen", code: "YE", iso3: "YEM", dial_code: "+967" },
	{ name: "Zambia", code: "ZM", iso3: "ZMB", dial_code: "+260" },
	{ name: "Zimbabwe", code: "ZW", iso3: "ZWE", dial_code: "+263" },
];
